# Generated by Django 5.2.5 on 2025-08-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da consulta', null=True),
        ),
    ]
